### PR TITLE
28 rebuild site navbar

### PR DESCRIPTION
**Pull request by kevinthuhstink**
if anyone knows any better search bar components do tell
this search bar is frustrating to work with

search bar component from here: https://github.com/moroshko/react-autosuggest

### CODE REVIEW

**Comment by EddisonSo** [comment]
Please remove all instances of pycache...

**Comment by kevinthuhstink** [comment]
oops fixed

**Comment by EddisonSo** [comment]
I am still seeing pycache files

**Comment by iscii** [comment]
@kevinthuhstink phenomenal joberoonies. adding on to above pycache issues, navbar doesn't keep its build when signed out; pls make it persistent

**Pull request closed without merging**
